name: Build WP Cache

on:
  schedule:
    - cron: '0 3 * * *' # Her gün saat 03:00'te (UTC) - Türkiye saati 06:00
  workflow_dispatch:
  repository_dispatch:
    types: [wp_published]

permissions:
  contents: write

jobs:
  build-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build WP cache
        env:
          PUBLIC_WORDPRESS_API_URL: https://dsgservisi.com/wp-json/wp/v2
          PUBLIC_WORDPRESS_PROXY_URL: https://wordpress-proxy-dsgservisi.dsgservisi.workers.dev/wp-json/wp/v2
        run: node scripts/build-wp-cache.mjs

      - name: Download featured images
        run: node scripts/build-wp-images.mjs

      - name: Download and rewrite content images
        run: node scripts/build-wp-content-images.mjs || echo "content images step skipped"

      - name: Commit and push changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/wp-cache/
            git commit -m "chore(cache): update WP cache (posts, images)"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Trigger Vercel deploy (optional)
        if: ${{ env.VERCEL_DEPLOY_HOOK_URL != '' }}
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$VERCEL_DEPLOY_HOOK_URL" || echo "Deploy hook failed or not set"


