name: Build WP Cache

on:
  schedule:
    - cron: '0 * * * *' # hourly
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build WP cache
        env:
          PUBLIC_WORDPRESS_API_URL: https://dsgservisi.com/wp-json/wp/v2
        run: node scripts/build-wp-cache.mjs

      - name: Commit and push changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/wp-cache/posts.json
            git commit -m "chore(cache): update WP posts cache"
            git push
          else
            echo "No changes to commit."
          fi


